version: 2

updates:
  - package-ecosystem: pip
    directory: "/template"
    schedule:
      interval: daily
      time: "19:00"
      timezone: "Asia/Kolkata"
    groups:
      python-packages:
        patterns:
          - "*"
